export const cardArray = [
  {
    id: 0,
    title: 'Первый товар',
    price: '170 ₽',
    address: 'Казань, р-н Вахитовский 1',
    date: '10 июля 11:39',
    img: '/image/card-img.jpg',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 1,
    title: 'Второй товар',
    price: '171 ₽',
    address: 'Казань, р-н Вахитовский 2',
    date: '11 июля 11:39',
    img: '/image/card-img.jpg',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 2,
    title: 'Третий товар',
    price: '172 ₽',
    address: 'Казань, р-н Вахитовский 3',
    date: '12 июля 11:39',
    img: '/image/card-img.jpg',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 3,
    title: 'Четвертый товар',
    price: '173 ₽',
    address: 'Казань, р-н Вахитовский 4',
    date: '13 июля 11:39',
    img: '/image/card-img.jpg',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 4,
    title: 'Пятый товар',
    price: '174 ₽',
    address: 'Казань, р-н Вахитовский 5',
    date: '14 июля 11:39',
    img: '/image/card-img.jpg',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 5,
    title: 'Шестой товар',
    price: '175 ₽',
    address: 'Казань, р-н Вахитовский 6',
    date: '15 июля 11:39',
    img: '/image/card-img.jpg',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
];
